### ISSUE TITLE
Error while generating project into MacOSX El Capitan

### ISSUE THREAD

**Issue by sjalowoi** [jmfirth/generator-elm-spa#3]
Hi, 

I would like to use elm-spa generator for a future production web site, i encounter a problem after executing: yo elm-spa, below the stack trace (i have installed all prerequisites specified on readme):

Installing npm dependencies...
Installing Elm dependencies...
Packages configured successfully!
Building project...
/Users/sjalowoi/dev/src/savtime/web/webserver/frontend/Gulpfile.js:85
    postcss: (webpack) => {
                       ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Command failed: gulp build
/Users/sjalowoi/dev/src/savtime/web/webserver/frontend/Gulpfile.js:85
    postcss: (webpack) => {
                       ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

```
at checkExecSyncError (child_process.js:1346:13)
at execSync (child_process.js:1386:13)
at module.exports.yeoman.generators.Base.extend.install (/usr/local/lib/node_modules/generator-elm-spa/generators/app/index.js:96:9)
at /usr/local/lib/node_modules/generator-elm-spa/node_modules/yeoman-generator/lib/base.js:430:16
at processImmediate [as _immediateCallback] (timers.js:367:17)
```

Could you help me to resolve this problem ? 
Thanks in advance
Sylvain

**Comment by sjalowoi** [comment]
Sorry, i have a too old version of node JS, i close issue.
Sylvain
